"""
Program: Final_MEstrada.py
Create program where you, the user, saves a princess from an "evil" dragon.


- Input name to personalize story adventure.
- Build backstory for adventure game. 
-- Complete a task before leaving rooms/areas.
-- Collect items from these tasks.
-- Create inventory. Accessible at any time. 
-- Use simple commands.
- Define ending.
-- Have 2 different types of endings, one where the princess survives and one
    where she doesn't. 

"""
import sys
import time
import __main__

#Choice options throughout story
answer1 = ["1"]
answer2 = ["2"]
answer3 = ["3"]
answer4 = ["4"]
answer5 = ["5"]
answer6 = ["6"]
answer7 = ["7"]
answer8 = ["8"]

#Dictionary - of key players in the story
di = {'Princess Aurora', 'Spartan the Dragon', 'playerName', 'Skeleton'}

#Possible Lists - 1 is for path of impatience, 2 is for path of patience
bagItems1 = ['You ran out of your house with nothing in hand, remember?']
bagItems1a = ['You ran out of your house with nothing in hand, remember?', 'Good thing the skeleton gave you the Potion of Orclev!']
bagItems2 = ['rose.', 'red sash.', 'food.', 'clean underwear.', 'good luck charm.', 'new socks.', 'change of clothes.', 'The Dagger of Hope.']

#Forces an answer
required = ("\nYou must pick a choice! Please use only the appropriate number in your response!")

#introduction to the game - a.k.a. my "main" code

def intro():
    print("==========================================================================================")
    time.sleep(4)
    print("Welcome to the beginning of the rest of your life.")
    time.sleep(2)
    print("Do you think you can save your other half?")
    time.sleep(2)
    print("...Or will you make the ultimate sacrifice?")
    time.sleep(2)
    print("Choose wisely.")
    time.sleep(2)
    print("Your lives are in your hands!")
    time.sleep(3)
    print("Now, ",playerName,". Think through your choices carefully. You have all the time in the world to be smart about what you do.")
    time.sleep(4)
    print("Oh. And good luck...")
    time.sleep(3)
    print("You may need it.")
    print("==========================================================================================")
    time.sleep(3)
    print("You awake one foggy morning to the chirping sounds of the birds, on the floor of your home in Rosedale. You begin wondering why your head aches like a heavy drum was beating inside it.")
    time.sleep(5)
    print("You look at your bedside table and you see a glass of water, a red towel and a piece of paper.")
    time.sleep(4)
    print("Will you:")
    time.sleep(2)
    print("1. Drink the water?")
    time.sleep(2)
    print("2. Put the red towel in your pocket?")
    time.sleep(2)
    print("3. Read the note?")
    time.sleep(2)
    choice = input(">>> Pick a number: ")#Here is your first choice, and the choice code for how we will make choices for the rest of the game.
    if choice in answer1:
        optionGlass()
    elif choice in answer2:
        optionTowel()
    elif choice in answer3:
        optionNote()
    else:
        print(required)
        optionFirst()

def optionFirst():#restarts the first choice selection
    print("Will you:")
    time.sleep(2)
    print("1. Drink the water?")
    time.sleep(1)
    print("2. Put the red towel in your pocket?")
    time.sleep(1)
    print("3. Read the note?")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionGlass()
    elif choice in answer2:
        optionTowel()
    elif choice in answer3:
        optionNote()
    else:
        print(required)
        optionFirst()

def optionGlass():#drinking water! 
    print("Okay. Well. You're slightly hydrated now. Will you: ")
    time.sleep(1)
    print("1. Drink again from the glass of water?")
    time.sleep(2)
    print("2. Put the red towel in your pocket?")
    time.sleep(2)
    print("3. Read the note?")
    time.sleep(2)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionGlass1()
    elif choice in answer2:
        optionTowel()
    elif choice in answer3:
        optionNote()
    else:
        print(required)
        optionGlass()

def optionTowel():#option2 - will have other options that will either force you to hit game over or read the note
    print("Well, it's more of a sash... and you know she would hate you called it a towel!")
    time.sleep(2)
    print("But it smells faintly of her perfume... and it has her name engraved on it.")
    time.sleep(2)
    print("Aurora.")
    time.sleep(2)
    print("Will you: ")
    time.sleep(1)
    print("1. Drink from the glass of water?")
    time.sleep(2)
    print("3. Read the note?")
    time.sleep(2)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionGlass1()
    elif choice in answer3:
        option_note()
    else:
        print(required)
        optionTowel()

def optionGlass1():#Option for the slackers
    print("Really? Drinking more water? What are you afraid of?")
    time.sleep(2)
    print("Will you: ")
    time.sleep(1)
    print("1. Drink the last bit of the water?")
    time.sleep(2)
    print("2. Finally read the freakin' note?!?")
    time.sleep(2)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionGlass2()
    elif choice in answer2:
        optionNote()
    else:
        print(required)
        optionGlass1()

def optionGlass2():#Will end game if player does not read note - game over option
    print("The glass of water has now been emptied and your bladder is now worse off for wear.")
    time.sleep(3)
    print("Will you: ")
    time.sleep(1)
    print("1. Go to the bathroom?")
    time.sleep(2)
    print("2. Read the letter that's been waiting for you for a long time now?")
    time.sleep(2)
    choice = input(">>> Pick a number: ")    
    if choice in answer1:
        optionToilet()
    elif choice in answer2:
        optionNote()
    else:
        print(required)
        optionGlass2()

def optionToilet():#This is a game over option - Bad ending #1
    print("You've slacked off for far too long.")
    time.sleep(2)
    print("A snake jumps out of the toilet bowl and bites you in the neck before you can react.")
    time.sleep(4)
    print("You rip the snake off your neck but it's too late...")
    time.sleep(3)
    print("The poison from its fangs spreads rapidly through your entire system.")
    time.sleep(2)
    print("You have died...")
    time.sleep(5)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(3)
    print("You have not yet found the true ending. Will you restart the game?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    choice = input(">>> Pick a number: ")    
    if choice in answer1:
        time.sleep(2)
        intro()
    elif choice in answer2:
        time.sleep(2)
        print("You have stupidly chosen to end the program.")
        time.sleep(2)
        print("UNTIL NEXT TIME, ",playerName,"!")
        time.sleep(2)
        print("Goodbye.")

def optionNote():#this is where you read the note
    print("You've decided to open and read the note...")
    time.sleep(2)
    print("The note is scrawled in handwriting you do not recognize...")
    time.sleep(2)
    print("You've come to learn why your head hurts. It appears that an unknown force knocked you out while you were in the garden with your beloved Princess Aurora.")
    time.sleep(6)
    print("Where did she go?!?!")
    time.sleep(2)
    print("You look around frantically before continuing to read the letter...")
    time.sleep(4)
    print("You learn that a dragon swooped in and kidnapped her while you were knocked out.")
    time.sleep(2)
    print("The final lines of the letter inform you that it would benefit you to wait three whole days before you chase after this mysterious dragon.")
    time.sleep(4)
    print("If you choose to wait, you will earn a map directly to the heart of the dragon's cave and a new weapon.")
    time.sleep(3)
    print("If you choose to charge straight into the mouth of hell and fight this dragon with the Sword of Destiny, already at your side...")
    time.sleep(3)
    print("You will earn the map anyway but will forever lose the new weapon.")
    time.sleep(4)
    print("This is for her. Everything you do has always been for her.")
    time.sleep(2)
    print("You read the final line at the bottom of this letter.")
    time.sleep(2)
    print(" 'Your beloved Aurora is waiting for you.' ")
    time.sleep(3)
    print("Are you: ")
    time.sleep(2)
    print("1. Patient and potentially stupid?")
    time.sleep(2)
    print("2. Headstrong and fearless?")
    time.sleep(2)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        f = open("BagItems.txt", 'w')
        f.write("Rose.\nRed sash.\nFood.\nClean underwear.\nNew socks.\nChange of clothes.\nThe Dagger of Hope.\nLucky Charm.")
        f.close()
        optionWait()
    elif choice in answer2:
        optionDumb()
    else:
        print(required)
        optionNote1()

def optionNote1():#Restarts the note decision
    print("It's time to make a decision.")
    time.sleep(2)
    print("The beautiful Aurora is waiting for you.")
    time.sleep(2)
    print("Are you: ")
    time.sleep(2)
    print("1. Patient and potentially stupid?")
    time.sleep(2)
    print("2. Headstrong and fearless?")
    time.sleep(2)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        f = open("BagItems.txt", 'w')
        f.write("Rose.\nRed sash.\nFood.\nClean underwear.\nNew socks.\nChange of clothes.\nThe Dagger of Hope.\nLucky Charm.")
        f.close()
        optionWait()
    elif choice in answer2:
        optionDumb()
    else:
        print(required)
        optionNote1()
        
def optionWait():#This is the option to wait 3 days.
    print("As much as it pains you, you must remember you were raised with the patience of a saint.")
    time.sleep(3)
    print("The type of patience that eventually helped you win over Princess Aurora's heart.")
    time.sleep(3)
    print("You begin to do as you know Princess Aurora would want you to do.")
    time.sleep(3)
    print("You begin to collect items from your house that will aid you in your journey.")
    time.sleep(2)
    print("A rose, pulled straight from your garden. Planted by the Princess herself.")
    time.sleep(3)
    print("Food. Clean underwear. New socks.")
    time.sleep(2)
    print("Your good luck charm, given to you by your long dead father.")
    time.sleep(3)
    print("The Dagger of Hope.")
    time.sleep(2)
    print("The red sash given to you by the Princess.")
    time.sleep(2)
    print("And finally, a full change of clothes.")
    time.sleep(2)
    print("Once you are finished, you decide it's almost time to lie down.")
    time.sleep(2)
    print("Do you lay down immediately?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionSleepy1()
    elif choice in answer2:
        optionSleepy1()
    else:
        print(required)
        optionWait1()

def optionWait1():#resets option wait
    print("Do you lay down?")
    time.sleep(2)
    choice = input(">>>Pick a number: ")
    time.sleep(2)
    print("1. Yes. Sleep for the three full days.")
    time.sleep(1)
    print("2. No. Stay up just a little bit longer.")
    if choice in answer1:
        optionSleepy1()
    elif choice in answer2:
        optionSleepy1()
    else:
        print(required)
        optionWait1()

def optionSleepy1():#Will put you to sleep anyway for the 3 days. It is the patient path.
    print("Your eyelids are heavy but your heart hurts too much to sleep.")
    time.sleep(2)
    print("You reach for the whiskey and drink straight from the bottle.")
    time.sleep(3)
    print("As if magic from the angels themselves, you begin to feel more drowsy than before.")
    time.sleep(3)
    print("As you fall asleep, you hear her voice...")
    time.sleep(2)
    print(" 'The rose.' ")
    time.sleep(3)
    option3days()

def optionDumb():#This is the impatient path, where you collect virtually nothing and set out to find your princess.
    print("'To hell with waiting!' you say.")
    time.sleep(2)
    print("Your riches weren't gained by sitting around and the Princess wasn't ever ashamed of your strong will.")
    time.sleep(2)
    print("You leave everything behind except The Sword of Destiny and an empty bag.")
    time.sleep(2)
    print("As you exit your house, a strong wind blows.")
    time.sleep(2)
    print("A map flutters its way across the ground.")
    time.sleep(2)
    print("As you bend to pick it up, you see that the words 'dragon' and 'cave' are written in what appears to be dried, red blood.")
    time.sleep(4)
    print("You grin.")
    time.sleep(2)
    print("The gods have always looked after you.")
    time.sleep(2)
    print("You are now ready.")
    time.sleep(2)
    print("Princess Aurora awaits.")
    optionCave1()

def option3days():#This is where you wake up 3 days later
    print("You awake, three days later, in a peaceful manner.")
    time.sleep(2)
    print("You are ready.")
    time.sleep(2)
    print("Princess Aurora awaits.")
    time.sleep(2)
    print("You reach for your sword, 'The Sword of Destiny', and your packed bag.")
    time.sleep(2)
    print("As you open the door, there is a crack of thunder from above that knocks you onto your back.")
    time.sleep(2)
    print("Five feet in front of you, a powerful looking sword sticks out of the dirt.")
    time.sleep(2)
    print("You see something engraved on the blade itself... 'The Dragon's Lament'.")
    time.sleep(3)
    print("...what is this? There's a map attached to the hilt of the sword by string?")
    time.sleep(4)
    print("You grin.")
    time.sleep(2)
    print("The gods have always looked after you.")
    time.sleep(2)
    print("You throw aside The Sword of Destiny and grab The Dragon's Lament instead.")
    time.sleep(4)
    print("You are now ready.")
    time.sleep(2)
    print("Princess Aurora awaits.")
    time.sleep(3)
    optionCave2()

#IMPORTANT NOTE BELOW    
"""FROM HERE ON OUT, FUNCTIONS WITH 1 OR 1(letter) AFTER IT WILL BE THE IMPATIENT PATH AND
    FUNCTIONS WITH 2 OR 2(letter) AFTER IT WILL BE THE PATIENT PATH.

    BOTH PATHS WILL BE SIMILAR BUT HAVE MINOR DIALOGUE CHANGES.

    ALL OF THE IMPATIENCE PATH WILL BE FIRST.

    THE PATIENCE PATH WILL AFTER ALL THE IMPATIENT STUFF."""
#IMPORTANT NOTE ABOVE

def optionCave1():#Path of Impatience
    print("You have used the map to arrive at your destination.")
    time.sleep(3)
    print("As you near the entrance, a rotted skeleton appears in front of you.")
    time.sleep(2)
    print("You draw your sword, The Sword of Destiny, and steady your breathing.")
    time.sleep(2)
    print("The skeleton laughs.")
    time.sleep(1)
    print("'",playerName,", you mean to harm me?'")
    time.sleep(3)
    print("'Hmmm. Perhaps...'")
    time.sleep(3)
    print("'You may perhaps prove me wrong yet.'")
    time.sleep(3)
    print("You wait, saying nothing.")
    time.sleep(2)
    print("'I have some information for you, ",playerName,".'")
    time.sleep(3)
    print("'Inside this cave lies a sleeping dragon and your precious princess.'")
    time.sleep(3)
    print("The way the skeleton spits out the word princess fills you with anger...")
    time.sleep(4)
    print("But still, you wait.")
    time.sleep(2)
    print("'Will you hear me out or will you be the bull in a china shop I know you to be and just charge into the cave?'")
    time.sleep(4)
    print("What will you do?")
    time.sleep(2)
    print("1. Listen")
    time.sleep(1)
    print("2. Ignore")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionListen1()
    elif choice in answer2:
        optionIgnore1()
    else:
        print(required)
        optionCave1a()

def optionCave1a():#Resets skeleton option
    print("'I'll ask once more. What will you decide?'")
    time.sleep(2)
    print("1. Listen")
    time.sleep(1)
    print("2. Ignore")
    choice = input(">>> Pick a number: ")    
    if choice in answer1:
        optionListen1()
    elif choice in answer2:
        optionIgnore1()
    else:
        print(required)
        optionCave1b()

def optionCave1b():#Ends skeleton option
    print("'I am done asking.'")
    time.sleep(2)
    print("'Good luck.'")
    time.sleep(2)
    print("The skeleton disappears and you move forward.")
    optionBag1()

def optionIgnore1():#Ignores everything about the skeleton
    print("You've chosen to ignore the skeleton.")
    time.sleep(3)
    print("The skeleton disappears.")
    time.sleep(2)
    print("Though you can't help but to think maybe you should have listened, you move forward anyway.")
    time.sleep(5)
    print("You move forward into the cave and again ready The Sword of Destiny.")
    optionBag1()
      
def optionListen1():#Path of impatience - listening to the skeleton
    print("The skeleton laughs again.")
    time.sleep(1)
    print("'",playerName,", you are the first in 600 years to ever listen.'")
    time.sleep(3)
    print("'Hmmm. Perhaps...' it begins.")
    time.sleep(3)
    print("'You may perhaps prove me wrong yet.' it continues.")
    time.sleep(3)
    print("You wait, saying nothing, but the word attack floats into your head.")
    time.sleep(2)
    print("'Just so you know, ",playerName,", there is a deadly potion that will kill this dragon without you ever needing to raise your blade.'")
    time.sleep(5)
    print("'All you would have to do is say the word and I will conjure this for you.'")
    time.sleep(3)
    print("'You could, however, ignore this special potion and kill the dragon with your blade.")
    time.sleep(4)
    print("The skeleton sneers.")
    time.sleep(2)
    print("...and still, you wait, much unlike you are known to do.")
    time.sleep(5)
    print("\'Is that it?\' you ask.")
    time.sleep(3)
    print("The skeleton's sneer turns into a curious smile.")
    time.sleep(3)
    print("\'Well, since you asked so kindly...\'")
    time.sleep(3)
    print("\'You could always try talking to the dragon. His name is Spartan.\'")
    time.sleep(4)
    print("You stare in disbelief...")
    time.sleep(3)
    print("'Make your choice, ",playerName,".\'")
    time.sleep(2)
    print("1. Ask to conjure the potion.")
    time.sleep(1)
    print("2. Decide to use your blade.")
    time.sleep(1)
    print("3. Decide to talk to the dragon.")
    choice = input(">>> Pick a number: ")
    time.sleep(2)
    if choice in answer1:
        optionPotion1()
    elif choice in answer2:
        optionBlade1()
    elif choice in answer3:
        optionTalk1()
    else:
        print(required)
        optionListen1a()

def optionListen1a():#Resets skeleton choice, will be infinite, as the game has progressed too far now to end abruptly.
    print("\'Make your choice, ",playerName,".\'")
    time.sleep(2)
    print("1. Ask to conjure the potion.")
    time.sleep(1)
    print("2. Decide to use your blade.")
    time.sleep(1)
    print("3. Decide to talk to the dragon.")
    choice = input(">>> Pick a number: ")
    time.sleep(2)
    if choice in answer1:
        optionPotion1()
    elif choice in answer2:
        optionBlade1()
    elif choice in answer3:
        optionTalk1()
    else:
        print(required)
        optionListen1a()

def optionPotion1():#path of impatience - using the black potion
    print("You sheath your blade.")
    time.sleep(2)
    print("\'Interesting choice, ",playerName,". But your wish is my command.\'")
    time.sleep(3)
    print("There is suddenly a blinding flash of light.")
    time.sleep(3)
    print("When your sight is back in focus, you realize the skeleton is gone.")
    time.sleep(3)
    print("In its place is a small vial filled with a dark black liquid.")
    time.sleep(3)
    print("You stuff the vial into your pocket and run into the cave.")
    optionBag1a()

def optionBlade1():#path of impatience - using the sword
    print("You lower your blade.")
    time.sleep(2)
    print("\'I will live and die by this blade.\' you say.")
    time.sleep(2)
    print("\'Interesting choice, ",playerName,". But your wish is my command.\' says the skeleton")
    time.sleep(4)
    print("There is suddenly a blinding flash of light.")
    time.sleep(3)
    print("When your sight is back in focus, you realize the skeleton is gone.")
    time.sleep(3)
    print("You take a deep breath and run into the cave.")
    optionBlade1a()
    
def optionTalk1():#path of impatience - talking option
    print("You sheath your blade.")
    time.sleep(2)
    print("\'I\'ve always wanted to try a different way.' you say.")
    time.sleep(3)
    print("You continue... \'I will talk to this dragon of yours.\'")
    time.sleep(2)
    print("\'Interesting choice, ",playerName,". But your wish is my command.'")
    time.sleep(3)
    print("There is suddenly a blinding flash of light.")
    time.sleep(3)
    print("When your sight is back in focus, you realize the skeleton is gone.")
    time.sleep(3)
    print("You feel good about your choice.")
    time.sleep(3)
    print("You steady your will and rush forward into the cave.")
    optionBag1a()#without potion

def optionBlade1a(): #Path of impatience - bad ending #2
    print("You eventually find your way to the darkest part of the cave.")
    time.sleep(3)
    print("It is fairly dark but you are prepared for the end.")
    time.sleep(3)
    print("You smell the dragon before you see it.")
    time.sleep(3)
    print("Both the dragon and the Princess sleep peacefully.")
    time.sleep(3)
    print("Though the Princess seems very blue...")
    time.sleep(3)
    print("You have made your decision.")
    time.sleep(3)
    print("You sneak forward to the neck of the sleeping dragon.")
    time.sleep(4)
    print("You raise your blade and bring it down in one fell swoop.")
    time.sleep(2)
    print("There is not so much as a peep from the dragon but you do hear laughter behind you.")
    time.sleep(3)
    print("You recognize the voice of the skeleton.")
    time.sleep(3)
    print("'Run to your princess, ",playerName,"! You IDIOT!'")
    time.sleep(2)
    print("As you run over to your bethrothed, you notice she has also been decapitated.")
    time.sleep(5)
    print("You hear the laugh again as you turn around.")
    time.sleep(3)
    print("The skeleton appears again.")
    time.sleep(3)
    print("'Maybe next time, you will think about your choices!' says the skeleton.")
    time.sleep(4)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(4)
    print("You have not yet found the true ending. Will you restart the game?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        time.sleep(2)
        intro()
    elif choice in answer2:
        time.sleep(2)
        print("You have stupidly chosen to end the program.")
        time.sleep(2)
        print("UNTIL NEXT TIME, ",playerName,"!")
        time.sleep(2)
        print("Goodbye.")

def optionBag1(): #path of impatience - without potion - comes from talk option.
    print("You\'ve decided, for some reason, to damn all weapon options and talk to the dragon.")
    time.sleep(4)
    print("The dragon stirs in the dim light.")
    time.sleep(2)
    print("'Hello? Mister Spartan, sir?' you say, more timidly than you would expect.")
    time.sleep(3)
    print("Suddenly the dragon roars!")
    time.sleep(2)
    print("You duck behind a pile of rocks as a fireball shoots five feet above your head!!!")
    time.sleep(5)
    print("'WHO DARES DISTURB ME TODAY?!' growls the dragon.")
    time.sleep(3)
    print("'AND MORE IMPORTANTLY... HOW DO YOU KNOW MY NAME?!'")
    time.sleep(3)
    print("You steady your breath.")
    time.sleep(2)
    print("'Sir, my name is",playerName,"!' you manage to weakly say.")
    time.sleep(3)
    print("'There was a skeleton outside and...'")
    time.sleep(2)
    print("'HA HA HA!' laughs the dragon. He seemed... amused?")
    time.sleep(2)
    print("'HE... HE IS ME. HE IS... HE IS WHO I USED TO BE.'")
    time.sleep(4)
    print("'WHAT DID HE TELL YOU?' Spartan grumbles softly.")
    time.sleep(2)
    print("'All he mentioned was to talk to you.' you reply.")
    time.sleep(3)
    print("'VERY WELL. I KNOW WHAT HE MEANS.' says Spartan.")
    time.sleep(3)
    print("The dragon gestures and the princess awakes.")
    time.sleep(3)
    print("'YOU MAY APPROACH.'")
    time.sleep(4)
    print("You near your princess and you notice she has a small vial in her left hand.")
    time.sleep(4)
    print("The vial contains a liquid that glows white.")
    time.sleep(2)
    print("'You have a choice here,",playerName,".' Princess Aurora begins.")
    time.sleep(2)
    print("'You can either give this to Spartan and liberate him...' she continues.")
    time.sleep(3)
    print("'...or you can destroy this vial and we can leave this place forever.'")
    time.sleep(3)
    print("'If you let Spartan drink this, you will take his place until the next brave soul comes to hopefully break this cycle.'")
    time.sleep(5)
    print("'So what will you do?' she finishes.")
    time.sleep(2)
    print("1. Give Spartan the potion.")
    time.sleep(1)
    print("2. Don't give Spartan the potion.")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionPotionEnd1()
    elif choice in answer2:
        optionPotionEnd1a()
    else:
        print(required)
        optionBag1repeat()

def optionBag1repeat():#repeats previous option, loops forever.
    print("'So what will you do?' Aurora says again.")
    time.sleep(2)
    print("1. Give Spartan the potion.")
    time.sleep(1)
    print("2. Don't give Spartan the potion.")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionPotionEnd1()
    elif choice in answer2:
        optionPotionEnd1a()
    else:
        print(required)
        optionBag1repeat()

def optionPotionEnd1():#bad ending number 3 - Give the white potion to the dragon
    print("You take the potion from Princess Aurora and turn toward the dragon.")
    time.sleep(4)
    print("You don't really want to do this but you feel you must.")
    time.sleep(2)
    print("'I understand what sacrifice is.' you begin, as you look at your princess one last time.")
    time.sleep(3)
    print("'If anyone else had asked, I would have never done this... but she did.'")
    time.sleep(3)
    print("'She is my whole world.'")
    time.sleep(2)
    print("'Here you go, Spartan... be free.' you finish.")
    time.sleep(4)
    print("Spartan, the dragon, disappears from this plane of existence.")
    time.sleep(3)
    print("You turn to apologize to Aurora but realize she is also gone...")
    time.sleep(3)
    print("...almost as if she were never really there.")
    time.sleep(3)
    print("Your heart begins to beat like a jackhammer.")
    time.sleep(2)
    print("Wings grow from your back and scales grow all over your skin.")
    time.sleep(3)
    print("Your heart beats out of your chest and transforms into a bloody skeleton.")
    time.sleep(3)
    print("Your skeleton disappears from view and your transformation is complete.")
    time.sleep(3)
    print("Exhausted, you lay your head down and await the heart of a true champion.")
    time.sleep(3)
    print("The Dragon\'s Lament, indeed...")
    time.sleep(4)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(4)
    print("You have not yet found the true ending. Will you restart the game?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        time.sleep(2)
        intro()
    elif choice in answer2:
        time.sleep(2)
        print("You have stupidly chosen to end the program.")
        time.sleep(2)
        print("UNTIL NEXT TIME, ",playerName,"!")
        time.sleep(2)
        print("Goodbye.")

def optionPotionEnd1a():#bad ending number 4 - Don't give the white potion to the dragon
    print("You take the potion from the Princess and think for a second.")
    time.sleep(4)
    print("You decide to grab Princess Aurora's hand...")
    time.sleep(2)
    print("...and run.")
    time.sleep(3)
    print("'RUN!!!' you yell, as you pull Princess Aurora and move your scrawny little legs away from the dragon.")
    time.sleep(4)
    print("Behind you, Spartan the dragon roars in anger.")
    time.sleep(3)
    print("The roars shake loose boulders but you dodge them all on your way out of the cave.")
    time.sleep(3)
    print("You run until you both cannot run anymore.")
    time.sleep(3)
    print("Exhausted, you collapse somewhere covered in sweat.")
    time.sleep(4)
    print("'I am sorry, my love.' you begin to say.")
    time.sleep(3)
    print("'No need to apologize. I understand your selfishness.' she replies.")
    time.sleep(3)
    print("'Besides,' she continues...")
    time.sleep(3)
    print("'We are both alive.'")
    time.sleep(3)
    print("You nod in agreement.")
    time.sleep(2)
    print("But still...")
    time.sleep(2)
    print("You cannot help the feeling that you could have done better.")
    time.sleep(3)
    print("The Dragon\'s Lament, indeed...")
    time.sleep(4)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(4)
    print("You have not yet found the true ending. Will you restart the game?")
    time.sleep(1)
    print("1. Yes")
    time.sleep(2)
    print("2. No")
    time.sleep(2)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        time.sleep(2)
        print("You have not yet found the true ending. Will you restart the game?")
        time.sleep(2)
        intro()
    elif choice in answer2:
        time.sleep(2)
        print("You have stupidly chosen to end the program.")
        time.sleep(2)
        print("UNTIL NEXT TIME, ",playerName,"!")
        time.sleep(2)
        print("Goodbye.")
        
def optionBag1a(): #path of impatience - bad ending #5 with black potion
    print("You take the black potion from your pocket and turn toward the dragon.")
    time.sleep(3)
    print("You don't really want to do this but you feel you must.")
    time.sleep(2)
    print("You notice the dragon's mouth is slightly open and time your drop.")
    time.sleep(3)
    print("On the next snore, you pour the potion into the dragon's mouth.")
    time.sleep(3)
    print("The dragon's eyes open and fearing death, you turn to run.")
    time.sleep(3)
    print("However, instead of killing you...")
    time.sleep(2)
    print("...the dragon disappears.")
    time.sleep(2)
    print("Ecstatic, you turn toward the princess...")
    time.sleep(3)
    print("...only to realize SHE has transformed into a dragon!")
    time.sleep(3)
    print("Paralyzed with fear, you try and speak.")
    time.sleep(2)
    print("Your mouth opens but no words come out.")
    time.sleep(3)
    print("The new dragon grins.")
    time.sleep(3)
    print("Her mouth opens and envelops your body.")
    time.sleep(3)
    print("You are dead.")
    time.sleep(3)
    print("The Dragon\'s Lament, indeed...")
    time.sleep(4)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(4)
    print("You have not yet found the true ending. Will you restart the game?")
    time.sleep(1)
    print("1. Yes")
    time.sleep(2)
    print("2. No")
    time.sleep(2)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        time.sleep(2)
        intro()
    elif choice in answer2:
        time.sleep(2)
        print("You have stupidly chosen to end the program.")
        time.sleep(2)
        print("UNTIL NEXT TIME, ",playerName,"!")
        time.sleep(2)
        print("Goodbye.")
#important note below!
"""
everything above here is the full extent of the impatient path.
the patient path is below!
"""
#important note above!
def optionCave2():#Path of patience
    print("You have used the map to arrive at your destination.")
    time.sleep(3)
    print("As you near the entrance, a zombie like skeleton appears in front of you.")
    time.sleep(2)
    print("You draw your sword, The Dragon's Lament, and steady your breathing.")
    time.sleep(2)
    print("The skeleton laughs.")
    time.sleep(1)
    print("'",playerName,", you mean to harm me?' it begins.")
    time.sleep(3)
    print("'With THAT?' It laughs at you again.")
    time.sleep(2)
    print("'Hmmm. Perhaps...' it continues.")
    time.sleep(3)
    print("'You may perhaps prove me wrong yet.' it says.")
    time.sleep(3)
    print("You wait, saying nothing.")
    time.sleep(2)
    print("'I have some information for you, ",playerName,"!'")
    time.sleep(3)
    print("'Inside this cave lies a sleeping dragon and your precious princess.'")
    time.sleep(3)
    print("The way the skeleton spits out the word princess fills you with a calm fury...")
    time.sleep(4)
    print("But still, you wait.")
    time.sleep(2)
    print("'Will you hear me out or will you simply charge into the cave?'")
    time.sleep(2)
    print("1. Listen")
    time.sleep(1)
    print("2. Ignore")
    time.sleep(3)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionListen2()
    elif choice in answer2:
        optionIgnore2()
    else:
        print(required)
        optionCave2a()

def optionCave2a():#Resets skeleton option
    print("'I will ask once more. What will you decide?'")
    time.sleep(2)
    print("1. Listen")
    time.sleep(1)
    print("2. Ignore")
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionListen2()
    elif choice in answer2:
        optionIgnore2()
    else:
        print(required)
        optionCave2b()

def optionCave2b():#Ends skeleton option
    print("'I am done asking.'")
    time.sleep(2)
    print("'Good luck.'")
    time.sleep(2)
    print("The skeleton disappears and you move forward.")
    optionBag2()

def optionIgnore2():#Ignores everything about the skeleton
    print("You have chosen to fully ignore the skeleton.")
    time.sleep(3)
    print("The skeleton disappears.")
    time.sleep(2)
    print("Though you cannot help but to think maybe you should have listened, you move forward anyway.")
    time.sleep(5)
    print("You move forward into the cave and again ready The Dragon\'s Lament.")
    optionBag2()

def optionListen2():#Path of patience - listening
    print("The skeleton laughs again.")
    time.sleep(1)
    print("'",playerName,", you are the first in 6,000 years to ever listen.' it says.")
    time.sleep(3)
    print("'Hmmm. Perhaps...'")
    time.sleep(3)
    print("'You may perhaps prove me wrong yet.' it continues.")
    time.sleep(3)
    print("You wait, saying nothing, but the word 'patience' floats into your head.")
    time.sleep(2)
    print("'Just so you know, ",playerName,", there is a deadly potion that will kill this dragon without you ever needing to raise your blade.'")
    time.sleep(5)
    print("'All you'd have to do is say the word and I will conjure this for you.'")
    time.sleep(3)
    print("'You could, however, ignore this special potion and kill the dragon with your blade.")
    time.sleep(4)
    print("The skeleton sneers at you.")
    time.sleep(2)
    print("...and still, you wait, just like you are known to do.")
    time.sleep(5)
    print("'Is that it?' you ask.")
    time.sleep(3)
    print("The skeleton's sneer turns into a curious smile.")
    time.sleep(3)
    print("'Well, since you asked so kindly...'")
    time.sleep(3)
    print("'You could always try talking to the dragon. His name is Spartan.'")
    time.sleep(4)
    print("You stare in disbelief...")
    time.sleep(3)
    print("'Make your choice, ",playerName,".'")
    time.sleep(2)
    print("1. Ask to conjure the potion.")
    time.sleep(1)
    print("2. Decide to use your blade.")
    time.sleep(1)
    print("3. Decide to talk to the dragon.")
    choice = input(">>> Pick a number: ")
    time.sleep(2)
    if choice in answer1:
        optionPotion2()
    elif choice in answer2:
        optionBlade2()
    elif choice in answer3:
        optionTalk2()
    else:
        print(required)
        optionListen2a()

def optionListen2a():#Resets skeleton choice, will be infinite, as the game has progressed too far now to end abruptly.
    print("'Make your choice, ",playerName,".'")
    time.sleep(2)
    print("1. Ask to conjure the potion.")
    time.sleep(1)
    print("2. Decide to use your blade.")
    time.sleep(1)
    print("3. Decide to talk to the dragon.")
    choice = input(">>> Pick a number: ")
    time.sleep(2)
    if choice in answer1:
        optionPotion2()
    elif choice in answer2:
        optionBlade2()
    elif choice in answer3:
        optionTalk2()
    else:
        print(required)
        optionListen2a()

def optionPotion2():#path of patience - black potion
    print("You sheath your blade.")
    time.sleep(2)
    print("'Interesting choice, ",playerName,". But your wish is my command.'")
    time.sleep(3)
    print("There is suddenly a blinding flash of light.")
    time.sleep(3)
    print("When your sight is back in focus, you realize the skeleton is gone.")
    time.sleep(3)
    print("In its place is a small vial filled with a dark black liquid.")
    time.sleep(3)
    print("You stuff the vial into your pocket and run into the cave.")
    optionBag2a()

def optionBlade2():#path of patience - dragon's lament
    print("You lower your blade.")
    time.sleep(2)
    print("'I will live and die by this blade.' you say.")
    time.sleep(2)
    print("'Interesting choice, ",playerName,". But your wish is my command.' says the skeleton.")
    time.sleep(4)
    print("There is suddenly a blinding flash of light.")
    time.sleep(3)
    print("When your sight is back in focus, you realize the skeleton is gone.")
    time.sleep(3)
    print("You take a deep breath and run into the cave.")
    optionBlade2a()

def optionTalk2():#path of patience - talking things through
    print("You sheath your blade.")
    time.sleep(2)
    print("'I've always wanted to try a different way.' you say.")
    time.sleep(3)
    print("You continue... 'I will talk to this dragon of yours.'")
    time.sleep(2)
    print("'Interesting choice, ",playerName,". But your wish is my command.'")
    time.sleep(3)
    print("There is suddenly a blinding flash of light.")
    time.sleep(3)
    print("When your sight is back in focus, you realize the skeleton is gone.")
    time.sleep(3)
    print("You feel good about your choice.")
    time.sleep(3)
    print("You steady your will and rush forward into the cave.")
    optionBag2()

def optionBlade2a():#Path of patience - using the sword - Bad ending #7
    print("You eventually find your way to the darkest part of the cave.")
    time.sleep(3)
    print("It stinks of rotting bodies but you are prepared for the end.")
    time.sleep(3)
    print("You hear the dragon snore before you see it.")
    time.sleep(3)
    print("Both the dragon and the Princess sleep peacefully.")
    time.sleep(3)
    print("Though the Princess seems very pale...")
    time.sleep(3)
    print("You have made your decision.")
    time.sleep(3)
    print("You sneak forward to the neck of the sleeping dragon.")
    time.sleep(4)
    print("You raise your blade and bring it down in one fell swoop.")
    time.sleep(2)
    print("The sword gets stuck in the dragon's neck as you hear laughter behind you.")
    time.sleep(3)
    print("You recognize the voice of the skeleton.")
    time.sleep(3)
    print("'Run to your princess, ",playerName,"! YOU MESSED UP!' it cackles.")
    time.sleep(2)
    print("As you run over to your significant other, you notice she has also been decapitated.")
    time.sleep(5)
    print("You hear that horrid laugh again as you turn around.")
    time.sleep(3)
    print("The skeleton appears again.")
    time.sleep(3)
    print("'Maybe next time, you'll think harder about your choices!' says the skeleton.")
    time.sleep(4)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(4)
    print("Will you restart the game?")
    time.sleep(1)
    print("1. Yes")
    time.sleep(2)
    print("2. No")
    time.sleep(2)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        time.sleep(2)
        print("You have not yet found the true ending. Will you restart the game?")
        time.sleep(2)
        intro()
    elif choice in answer2:
        time.sleep(2)
        print("You have stupidly chosen to end the program.")
        time.sleep(2)
        print("UNTIL NEXT TIME, ",playerName,"!")
        time.sleep(2)
        print("Goodbye.")

def optionBag2(): #path of patience - without black potion - comes from talk option.
    print("You've decided, for some reason, to damn all weapon options and talk to the dragon.")
    time.sleep(4)
    print("The dragon stirs in the dim light.")
    time.sleep(2)
    print("'Hello? Mister Spartan, sir?' you say, more timidly than you would expect.")
    time.sleep(3)
    print("Suddenly the dragon roars!")
    time.sleep(2)
    print("You duck behind a pile of rocks as a giant paw swings ten feet above your head!!!")
    time.sleep(5)
    print("'WHO DARES DISTURB ME TODAY?!' growls the dragon.")
    time.sleep(3)
    print("'AND MORE IMPORTANTLY... HOW DO YOU KNOW MY NAME?!'")
    time.sleep(3)
    print("You steady your breath.")
    time.sleep(2)
    print("'Sir, my name is",playerName,"!' you manage to weakly say.")
    time.sleep(3)
    print("'There was a skeleton outside and...'")
    time.sleep(2)
    print("'HA HA HA!' laughs the dragon. It seemed... happy?")
    time.sleep(2)
    print("'HE... HE IS ME. HE IS... HE IS WHO I USED TO BE.'")
    time.sleep(4)
    print("'WHAT DID HE TELL YOU?' Spartan grumbles softly.")
    time.sleep(3)
    print("Well, as softly as a giant dragon can grumble, anyway.")
    time.sleep(3)
    print("'All he mentioned was to talk to you.' you reply.")
    time.sleep(3)
    print("'VERY WELL. I KNOW WHAT HE MEANS.' says Spartan.")
    time.sleep(3)
    print("The dragon gestures and the princess awakes.")
    time.sleep(3)
    print("'YOU MAY APPROACH.'")
    time.sleep(4)
    print("You near your princess and you notice she has a small vial in her left hand.")
    time.sleep(4)
    print("The vial contains a liquid that glows white.")
    time.sleep(2)
    print("'You have a choice here,",playerName,".' Princess Aurora begins.")
    time.sleep(2)
    print("'You can either give this to Spartan and liberate him...' she continues.")
    time.sleep(3)
    print("'...or you can destroy this vial and we can leave this place forever.'")
    time.sleep(3)
    print("'If you let Spartan drink this, you will take his place until the next brave soul comes to hopefully break this cycle.'")
    time.sleep(5)
    print("'So what will you do?' she finishes.")
    time.sleep(2)
    print("1. Give Spartan the potion.")
    time.sleep(1)
    print("2. Don't give Spartan the potion.")
    time.sleep(1)
    print("3. Other options?")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionPotionEnd2()
    elif choice in answer2:
        optionPotionEnd2a()
    elif choice in answer3():
        optionFinal2()
    else:
        print(required)
        optionBag2repeat()
        
def optionBag2repeat():#repeats previous option, loops forever.
    print("'So what will you do?' Aurora says again.")
    time.sleep(2)
    print("1. Give Spartan the potion.")
    time.sleep(1)
    print("2. Don't give Spartan the potion.")
    time.sleep(1)
    print("3. Other options?")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        optionPotionEnd2()
    elif choice in answer2:
        optionPotionEnd2a()
    elif choice in answer3:
        optionRose2()
    else:
        print(required)
        optionBag2repeat()

def optionPotionEnd2():#bad ending number 8 - Give the white potion to the dragon
    print("You take the white potion from Princess Aurora and turn toward the dragon.")
    time.sleep(4)
    print("You don't really want to do this but you feel you must.")
    time.sleep(2)
    print("'I understand what sacrifice is.' you begin, as you look at your princess one last time.")
    time.sleep(3)
    print("'If anyone else had asked, I would have never done this... but she did.'")
    time.sleep(3)
    print("'She is my whole world.'")
    time.sleep(2)
    print("'Here you go, Spartan... be free.' you finish.")
    time.sleep(4)
    print("Spartan, the dragon, opens his mouth and eats the Princess before you can react.")
    time.sleep(3)
    print("You turn, mouth open, staring in horror...")
    time.sleep(3)
    print("...almost as if you cannot believe what just happened.")
    time.sleep(3)
    print("Your heart begins to beat like a jackhammer.")
    time.sleep(2)
    print("Spartan the dragon burps....")
    time.sleep(3)
    print("and EXPLODES into a million pieces.")
    time.sleep(2)
    print("A piece of the dragon hits you and slams you into the nearest wall.")
    time.sleep(3)
    print("You die instantly.")
    time.sleep(3)
    print("The Dragon's Lament, indeed...")
    time.sleep(4)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(4)
    print("You have not yet found the true ending. Will you restart the game?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        intro()
    elif choice in answer2:
        print("You've chosen to end the program, weakling.")
        print("GAME OVER.")
        print("Goodbye.")

def optionPotionEnd2a():#bad ending number 9 - Don't give the white potion to the dragon
    print("You take the white potion from the Princess and think for a second.")
    time.sleep(4)
    print("You decide to grab Princess Aurora's hand...")
    time.sleep(2)
    print("...and run.")
    time.sleep(3)
    print("'RUN!!!' you yell, as you pull Princess Aurora and move your chubby little legs away from the dragon.")
    time.sleep(4)
    print("Behind you, Spartan the dragon roars in anger and disbelief.")
    time.sleep(3)
    print("The roars shake loose boulders but you dodge them all on your way out of the cave.")
    time.sleep(3)
    print("You run until you both cannot run anymore.")
    time.sleep(3)
    print("Exhausted, you collapse somewhere far away, covered in sweat.")
    time.sleep(4)
    print("'I am sorry, my love.' you begin to say.")
    time.sleep(3)
    print("'No need to apologize. I understand your selfishness.' she replies.")
    time.sleep(3)
    print("'Besides,' she continues...")
    time.sleep(3)
    print("'We are both alive.'")
    time.sleep(3)
    print("You nod in agreement.")
    time.sleep(2)
    print("'But still...' she begins to say.")
    time.sleep(2)
    print("'I cannot be with someone so stupidly selfish.'")
    time.sleep(3)
    print("'Goodbye forever,",playerName,". I wish to never see you again.'")
    time.sleep(4)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(4)
    print("You have not yet found the true ending. Will you restart the game?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        intro()
    elif choice in answer2:
        print("You've chosen to end the program, weakling.")
        print("GAME OVER.")
        print("Goodbye.")

def optionBag2a(): #path of patience - with black potion - bad ending #10
    print("You take the black potion from your pocket and turn toward the dragon.")
    time.sleep(3)
    print("You don't really want to do this but you feel you must.")
    time.sleep(2)
    print("You notice the dragon's mouth is slightly open and you time your drop.")
    time.sleep(3)
    print("On the next snore, you pour the black potion into the dragon's mouth.")
    time.sleep(3)
    print("The dragon's eyes open and fearing death, you turn to run.")
    time.sleep(3)
    print("However, instead of killing you immediately...")
    time.sleep(2)
    print("...the dragon disappears.")
    time.sleep(2)
    print("Ecstatic, you turn toward the princess...")
    time.sleep(3)
    print("...only to realize SHE has transformed into a zombie!")
    time.sleep(3)
    print("Paralyzed with fear, you try and speak.")
    time.sleep(2)
    print("Your mouth opens but no words come out.")
    time.sleep(3)
    print("The new zombie grins.")
    time.sleep(3)
    print("Her mouth opens and rips your neck your body.")
    time.sleep(3)
    print("You are dead.")
    time.sleep(4)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(4)
    print("You have not yet found the true ending. Will you restart the game?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        intro()
    elif choice in answer2:
        print("You've chosen to end the program, weakling.")
        print("GAME OVER.")
        print("Goodbye.")

def optionFinal2(): #Finally... the true ending... almost!
    print("Spartan the dragon cocks his head toward you, as does the Princess.")
    time.sleep(4)
    print("'...Could it be?' you hear from behind you.")
    time.sleep(3)
    print("You no longer have to turn to know who it was.")
    time.sleep(3)
    print("The skeleton shuffles forward and stands near the dragon.")
    time.sleep(3)
    print("'Nobody has ever asked for a different option before.' say the dragon and the skeleton simultaneously.")
    time.sleep(5)
    print("But still, you have a feeling you're close to the end.")
    time.sleep(3)
    print("Princess Aurora asks what is in your bag.")
    time.sleep(2)
    print("'This old thing?' you wonder aloud.")
    time.sleep(3)
    print("'Maybe I should look inside it...'")
    time.sleep(3)
    print("Do you look inside your bag?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    choice = input(">>> Pick a number:")
    if choice in answer1:
        optionRose2b()
    elif choice in answer2:
        optionRose2a()
    else:
        print(required)
        optionRose2c()

def optionRose2c(): #loops forever!!!!!!!!!!
    print("Do you look inside your bag?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    choice = input(">>> Pick a number:")
    if choice in answer1:
        optionRose2b()
    elif choice in answer2:
        optionRose2a()
    else:
        print(required)
        optionRose2c()

def optionRose2a(): #bad ending#11
    print("'IT'S FINE.' says Spartan.")
    time.sleep(3)
    print("'YOU MAY GO'. he finishes.")
    time.sleep(3)
    print("You take Princess Aurora's hand and walk out, unscathed.")
    time.sleep(3)
    print("The skeleton shuffles forward and stands near the dragon.")
    time.sleep(3)
    print("'Maybe someday...' wonders the skeleton.")
    time.sleep(3)
    print("You can't shake the feeling you were very close to something special.")
    time.sleep(5)
    print("Perhaps an item in your bag would have worked...")
    time.sleep(4)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(4)
    print("You have not yet found the true ending. Will you restart the game?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        time.sleep(2)
        intro()
    elif choice in answer2:
        time.sleep(2)
        print("You have stupidly chosen to end the program.")
        time.sleep(2)
        print("UNTIL NEXT TIME, ",playerName,"!")
        time.sleep(2)
        print("Goodbye.")

def optionRose2b(): #this leads to the game's three final choices... after the yes/no stuff.
    print("You can't believe you forgot about the items in your bag!")
    time.sleep(3)
    print("Do you need a reminder of what you had?")
    time.sleep(3)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    choice = input(">>> Pick a number: ")    
    if choice in answer1:
        f = open("BagItems.txt", 'r')
        while True:
            line = f.readline()
            if line == "":
                break
            print(line)
        time.sleep(4)
        optionGiveItem()
    elif choice in answer2:
        optionGiveItem()
    else:
        print(required)
        optionRose2b()

def optionRose2a1():#bad ending #11
    print("'I APPRECIATE YOUR GIFT.' says Spartan.")
    time.sleep(3)
    print("'YOU MAY GO'. he finishes.")
    time.sleep(3)
    print("You take Princess Aurora's hand and walk out, unscathed.")
    time.sleep(3)
    print("The skeleton shuffles forward and stands near the dragon.")
    time.sleep(3)
    print("'Maybe someday...' wonders the skeleton.")
    time.sleep(3)
    print("You can't shake the feeling you were very close to something special.")
    time.sleep(5)
    print("Perhaps another item in your bag would have worked...")
    time.sleep(4)
    print("G - A - M - E \ O - V - E - R")
    time.sleep(4)
    print("You have not yet found the true ending. Will you restart the game?")
    time.sleep(2)
    print("1. Yes")
    time.sleep(1)
    print("2. No")
    time.sleep(1)
    choice = input(">>> Pick a number: ")
    if choice in answer1:
        time.sleep(2)
        intro()
    elif choice in answer2:
        time.sleep(2)
        print("You have stupidly chosen to end the program.")
        time.sleep(2)
        print("UNTIL NEXT TIME, ",playerName,"!")
        time.sleep(2)
        print("Goodbye.")

def optionGiveItem():#This is it... final options. Give dragon the rose, give dragon anything else.
    print("What would you give the dragon?")
    time.sleep(2)
    print("1. Red sash.")
    time.sleep(2)
    print("2. Food.")
    time.sleep(2)
    print("3. Clean underwear.")
    time.sleep(2)
    print("4. New socks.")
    time.sleep(2)
    print("5. The rose.")
    time.sleep(2)
    print("6. Change of clothes.")
    time.sleep(2)
    print("7. Your lucky charm.")
    time.sleep(2)
    print("8. The Dagger of Hope.")
    time.sleep(2)
    if choice in answer1:
        optionRose2a1()
    elif choice in answer2:
        optionRose2a1()
    elif choice in answer3:
         optionRose2a1()
    elif choice in answer4:
        optionRose2a1()
    elif choice in answer5:
        f = open("congrats.txt", 'w')
        f.write("You have completed the game and found the true ending.\nYour heart is at peace. Your princess by your side.\nYour guardian angel overhead.\nCongratulations!")
        f.close()
        optionTrueEnding()
    elif choice in answer6:
        optionRose2a1()
    elif choice in answer7:
        optionRose2a1()
    elif choice in answer8:
        optionRose2a1()
    else:
        print(required)
        optionDoItAgain()

def optionDoItAgain():
    print("What would you give the dragon?")
    time.sleep(2)
    print("1. Red sash.")
    time.sleep(2)
    print("2. Food.")
    time.sleep(2)
    print("3. Clean underwear.")
    time.sleep(2)
    print("4. New socks.")
    time.sleep(2)
    print("5. The rose.")
    time.sleep(2)
    print("6. Change of clothes.")
    time.sleep(2)
    print("7. Your lucky charm.")
    time.sleep(2)
    print("8. The Dagger of Hope.")
    time.sleep(2)
    if choice in answer1:
        optionRose2a1()
    elif choice in answer2:
        optionRose2a1()
    elif choice in answer3:
         optionRose2a1()
    elif choice in answer4:
        optionRose2a1()
    elif choice in answer5:
        f = open("congrats.txt", 'w')
        f.write("You have completed the game and found the true ending.\nYour heart is at peace. Your princess by your side.\nYour guardian angel overhead.\nCongratulations!")
        f.close()
        optionTrueEnding()
    elif choice in answer6:
        optionRose2a1()
    elif choice in answer7:
        optionRose2a1()
    elif choice in answer8:
        optionRose2a1()
    else:
        print(required)
        optionDoItAgain()

def optionTrueEnding():
    print("'I APPRECIATE YOUR GIFT.' says Spartan.")
    time.sleep(3)
    print("'YOU MAY GO'. he finishes.")
    time.sleep(3)
    print("As you turn to leave, there is another flash of white light.")
    time.sleep(3)
    print("You are blinded.")
    time.sleep(3)
    print("Spartan and the skeleton begin to scream, but is it from pain?")
    time.sleep(3)
    print("You wish to help but you cannot.")
    time.sleep(5)
    print("The light has now disappeared.")
    time.sleep(4)
    print("As your eyes begin to focus again, you see a faint red glow where Spartan the dragon once stood.")
    time.sleep(4)
    print("An...")
    time.sleep(2)
    print("...is that...")
    time.sleep(4)
    print("'Is that an angel?!?' you exclaim aloud.")
    time.sleep(3)
    print("'YES, MY DEAR",playerName,"! IT IS I. SPARTAN.'")
    time.sleep(4)
    print("'FOREVER FREED NOW, THANKS TO YOUR COURAGEOUS ACTIONS.'")
    time.sleep(3)
    print("'IT WAS A CURSE, PLANTED ON ME BY THE DEVIL HIMSELF.'")
    time.sleep(4)
    print("'SURELY, HE WILL NOT BE HAPPY... BUT I NO LONGER CARE.'")
    time.sleep(3)
    print("'I WILL FOREVER WATCH OVER YOU AND YOUR BELOVED PRINCESS AURORA.'")
    time.sleep(3)
    print("'MAY THE LIGHT GUIDE YOU IN ALL YOUR FUTURE ACTIVITIES.'")
    time.sleep(3)
    f = open("congrats.txt", 'r')
    while True:
        line = f.readline()
        if line =="":
            break
        print(line)

playerName = (input("Enter your name: "))#player name!
print("==========================================================================================")
intro()
